# Generated by Django 3.1.1 on 2020-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255, null=True)),
                ('u_password', models.CharField(max_length=255, null=True)),
                ('u_email', models.CharField(max_length=255, null=True)),
                ('u_phno', models.CharField(max_length=255, null=True)),
                ('u_address', models.CharField(max_length=255, null=True)),
                ('u_gst', models.CharField(max_length=255, null=True)),
                ('u_panno', models.CharField(max_length=255, null=True)),
                ('u_servicetaxno', models.CharField(max_length=255, null=True)),
                ('u_documents', models.CharField(max_length=255, null=True)),
                ('u_role', models.CharField(max_length=255, null=True)),
                ('u_status', models.CharField(max_length=255, null=True)),
                ('u_token', models.CharField(max_length=255, null=True)),
                ('u_otp', models.IntegerField(null=True)),
                ('u_otp_is_used', models.IntegerField(null=True)),
                ('u_createddate', models.DateTimeField(auto_now=True)),
                ('u_modifieddate', models.DateTimeField(auto_now=True)),
                ('u_createdby', models.IntegerField(null=True)),
                ('u_modifiedby', models.IntegerField(null=True)),
            ],
        ),
    ]
