# Generated by Django 3.1.1 on 2020-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uneed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='u_documents',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
